//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBGINTB_Builder.Lib.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GinTubEntities : DbContext
    {
        public GinTubEntities()
            : base("name=GinTubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddAction(Nullable<int> verbtype, Nullable<int> noun)
        {
            var verbtypeParameter = verbtype.HasValue ?
                new ObjectParameter("verbtype", verbtype) :
                new ObjectParameter("verbtype", typeof(int));
    
            var nounParameter = noun.HasValue ?
                new ObjectParameter("noun", noun) :
                new ObjectParameter("noun", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddAction", verbtypeParameter, nounParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddActionResult(Nullable<int> result, Nullable<int> action)
        {
            var resultParameter = result.HasValue ?
                new ObjectParameter("result", result) :
                new ObjectParameter("result", typeof(int));
    
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddActionResult", resultParameter, actionParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddArea(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddArea", nameParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddCharacter(string name, string description)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddCharacter", nameParameter, descriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddCharacterActionRequirement(Nullable<int> item, Nullable<int> action)
        {
            var itemParameter = item.HasValue ?
                new ObjectParameter("item", item) :
                new ObjectParameter("item", typeof(int));
    
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddCharacterActionRequirement", itemParameter, actionParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddEvent(string name, string description)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddEvent", nameParameter, descriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddEventActionRequirement(Nullable<int> item, Nullable<int> action)
        {
            var itemParameter = item.HasValue ?
                new ObjectParameter("item", item) :
                new ObjectParameter("item", typeof(int));
    
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddEventActionRequirement", itemParameter, actionParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddItem(string name, string description)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddItem", nameParameter, descriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddItemActionRequirement(Nullable<int> item, Nullable<int> action)
        {
            var itemParameter = item.HasValue ?
                new ObjectParameter("item", item) :
                new ObjectParameter("item", typeof(int));
    
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddItemActionRequirement", itemParameter, actionParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddJSONPropertyDataType(string datatype)
        {
            var datatypeParameter = datatype != null ?
                new ObjectParameter("datatype", datatype) :
                new ObjectParameter("datatype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddJSONPropertyDataType", datatypeParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddLocation(string name, string locationfile)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var locationfileParameter = locationfile != null ?
                new ObjectParameter("locationfile", locationfile) :
                new ObjectParameter("locationfile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddLocation", nameParameter, locationfileParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddMessage(string name, string text)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddMessage", nameParameter, textParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddMessageChoice(string name, string text, Nullable<int> message)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            var messageParameter = message.HasValue ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddMessageChoice", nameParameter, textParameter, messageParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddMessageChoiceResult(Nullable<int> result, Nullable<int> messagechoice)
        {
            var resultParameter = result.HasValue ?
                new ObjectParameter("result", result) :
                new ObjectParameter("result", typeof(int));
    
            var messagechoiceParameter = messagechoice.HasValue ?
                new ObjectParameter("messagechoice", messagechoice) :
                new ObjectParameter("messagechoice", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddMessageChoiceResult", resultParameter, messagechoiceParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddNoun(string text, Nullable<int> paragraphstate)
        {
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            var paragraphstateParameter = paragraphstate.HasValue ?
                new ObjectParameter("paragraphstate", paragraphstate) :
                new ObjectParameter("paragraphstate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddNoun", textParameter, paragraphstateParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddParagraph(Nullable<int> order, Nullable<int> room, Nullable<int> roomstate)
        {
            var orderParameter = order.HasValue ?
                new ObjectParameter("order", order) :
                new ObjectParameter("order", typeof(int));
    
            var roomParameter = room.HasValue ?
                new ObjectParameter("room", room) :
                new ObjectParameter("room", typeof(int));
    
            var roomstateParameter = roomstate.HasValue ?
                new ObjectParameter("roomstate", roomstate) :
                new ObjectParameter("roomstate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddParagraph", orderParameter, roomParameter, roomstateParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddParagraphState(string text, Nullable<int> paragraph)
        {
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            var paragraphParameter = paragraph.HasValue ?
                new ObjectParameter("paragraph", paragraph) :
                new ObjectParameter("paragraph", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddParagraphState", textParameter, paragraphParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> dev_AddPlayer(string username, string domainname, string domain, string password, Nullable<System.Guid> playerid)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var domainnameParameter = domainname != null ?
                new ObjectParameter("domainname", domainname) :
                new ObjectParameter("domainname", typeof(string));
    
            var domainParameter = domain != null ?
                new ObjectParameter("domain", domain) :
                new ObjectParameter("domain", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var playeridParameter = playerid.HasValue ?
                new ObjectParameter("playerid", playerid) :
                new ObjectParameter("playerid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("dev_AddPlayer", usernameParameter, domainnameParameter, domainParameter, passwordParameter, playeridParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddResult(string name, string jsondata, Nullable<int> resulttype)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var jsondataParameter = jsondata != null ?
                new ObjectParameter("jsondata", jsondata) :
                new ObjectParameter("jsondata", typeof(string));
    
            var resulttypeParameter = resulttype.HasValue ?
                new ObjectParameter("resulttype", resulttype) :
                new ObjectParameter("resulttype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddResult", nameParameter, jsondataParameter, resulttypeParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddResultType(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddResultType", nameParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddResultTypeJSONProperty(string jsonproperty, Nullable<int> datatype, Nullable<int> resulttype)
        {
            var jsonpropertyParameter = jsonproperty != null ?
                new ObjectParameter("jsonproperty", jsonproperty) :
                new ObjectParameter("jsonproperty", typeof(string));
    
            var datatypeParameter = datatype.HasValue ?
                new ObjectParameter("datatype", datatype) :
                new ObjectParameter("datatype", typeof(int));
    
            var resulttypeParameter = resulttype.HasValue ?
                new ObjectParameter("resulttype", resulttype) :
                new ObjectParameter("resulttype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddResultTypeJSONProperty", jsonpropertyParameter, datatypeParameter, resulttypeParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddRoom(string name, Nullable<int> x, Nullable<int> y, Nullable<int> z, Nullable<int> area)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var xParameter = x.HasValue ?
                new ObjectParameter("x", x) :
                new ObjectParameter("x", typeof(int));
    
            var yParameter = y.HasValue ?
                new ObjectParameter("y", y) :
                new ObjectParameter("y", typeof(int));
    
            var zParameter = z.HasValue ?
                new ObjectParameter("z", z) :
                new ObjectParameter("z", typeof(int));
    
            var areaParameter = area.HasValue ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddRoom", nameParameter, xParameter, yParameter, zParameter, areaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddRoomState(Nullable<System.DateTime> time, Nullable<int> location, Nullable<int> room)
        {
            var timeParameter = time.HasValue ?
                new ObjectParameter("time", time) :
                new ObjectParameter("time", typeof(System.DateTime));
    
            var locationParameter = location.HasValue ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(int));
    
            var roomParameter = room.HasValue ?
                new ObjectParameter("room", room) :
                new ObjectParameter("room", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddRoomState", timeParameter, locationParameter, roomParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddVerb(string name, Nullable<int> verbtype)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var verbtypeParameter = verbtype.HasValue ?
                new ObjectParameter("verbtype", verbtype) :
                new ObjectParameter("verbtype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddVerb", nameParameter, verbtypeParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> dev_AddVerbType(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("dev_AddVerbType", nameParameter);
        }
    
        public virtual int dev_ClearDatabase(string backupfile)
        {
            var backupfileParameter = backupfile != null ?
                new ObjectParameter("backupfile", backupfile) :
                new ObjectParameter("backupfile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ClearDatabase", backupfileParameter);
        }
    
        public virtual int dev_DeleteAllActionResultsForAction(Nullable<int> action)
        {
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllActionResultsForAction", actionParameter);
        }
    
        public virtual int dev_DeleteAllActionsForNoun(Nullable<int> noun)
        {
            var nounParameter = noun.HasValue ?
                new ObjectParameter("noun", noun) :
                new ObjectParameter("noun", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllActionsForNoun", nounParameter);
        }
    
        public virtual int dev_DeleteAllAreas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllAreas");
        }
    
        public virtual int dev_DeleteAllCharacterActionRequirementsForAction(Nullable<int> action)
        {
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllCharacterActionRequirementsForAction", actionParameter);
        }
    
        public virtual int dev_DeleteAllCharacters()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllCharacters");
        }
    
        public virtual int dev_DeleteAllEventActionRequirementsForAction(Nullable<int> action)
        {
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllEventActionRequirementsForAction", actionParameter);
        }
    
        public virtual int dev_DeleteAllEvents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllEvents");
        }
    
        public virtual int dev_DeleteAllItemActionRequirementsForAction(Nullable<int> action)
        {
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllItemActionRequirementsForAction", actionParameter);
        }
    
        public virtual int dev_DeleteAllItems()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllItems");
        }
    
        public virtual int dev_DeleteAllJSONPropertyDataTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllJSONPropertyDataTypes");
        }
    
        public virtual int dev_DeleteAllLocations()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllLocations");
        }
    
        public virtual int dev_DeleteAllMessageChoiceResultsForMessageChoice(Nullable<int> messagechoice)
        {
            var messagechoiceParameter = messagechoice.HasValue ?
                new ObjectParameter("messagechoice", messagechoice) :
                new ObjectParameter("messagechoice", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllMessageChoiceResultsForMessageChoice", messagechoiceParameter);
        }
    
        public virtual int dev_DeleteAllMessageChoicesForMessage(Nullable<int> message)
        {
            var messageParameter = message.HasValue ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllMessageChoicesForMessage", messageParameter);
        }
    
        public virtual int dev_DeleteAllMessages()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllMessages");
        }
    
        public virtual int dev_DeleteAllNounsForParagraphState(Nullable<int> paragraphstate)
        {
            var paragraphstateParameter = paragraphstate.HasValue ?
                new ObjectParameter("paragraphstate", paragraphstate) :
                new ObjectParameter("paragraphstate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllNounsForParagraphState", paragraphstateParameter);
        }
    
        public virtual int dev_DeleteAllParagraphsForRoomAndRoomState(Nullable<int> room, Nullable<int> roomstate)
        {
            var roomParameter = room.HasValue ?
                new ObjectParameter("room", room) :
                new ObjectParameter("room", typeof(int));
    
            var roomstateParameter = roomstate.HasValue ?
                new ObjectParameter("roomstate", roomstate) :
                new ObjectParameter("roomstate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllParagraphsForRoomAndRoomState", roomParameter, roomstateParameter);
        }
    
        public virtual int dev_DeleteAllParagraphStatesForParagraph(Nullable<int> paragraph)
        {
            var paragraphParameter = paragraph.HasValue ?
                new ObjectParameter("paragraph", paragraph) :
                new ObjectParameter("paragraph", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllParagraphStatesForParagraph", paragraphParameter);
        }
    
        public virtual int dev_DeleteAllResultsForActionResultType(Nullable<int> action)
        {
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllResultsForActionResultType", actionParameter);
        }
    
        public virtual int dev_DeleteAllResultsForMessageChoiceResultType(Nullable<int> messagechoice)
        {
            var messagechoiceParameter = messagechoice.HasValue ?
                new ObjectParameter("messagechoice", messagechoice) :
                new ObjectParameter("messagechoice", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllResultsForMessageChoiceResultType", messagechoiceParameter);
        }
    
        public virtual int dev_DeleteAllResultsForResultType(Nullable<int> resulttype)
        {
            var resulttypeParameter = resulttype.HasValue ?
                new ObjectParameter("resulttype", resulttype) :
                new ObjectParameter("resulttype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllResultsForResultType", resulttypeParameter);
        }
    
        public virtual int dev_DeleteAllResultTypeJSONPropertiesForResultType(Nullable<int> resulttype)
        {
            var resulttypeParameter = resulttype.HasValue ?
                new ObjectParameter("resulttype", resulttype) :
                new ObjectParameter("resulttype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllResultTypeJSONPropertiesForResultType", resulttypeParameter);
        }
    
        public virtual int dev_DeleteAllResultTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllResultTypes");
        }
    
        public virtual int dev_DeleteAllRoomsInArea(Nullable<int> area)
        {
            var areaParameter = area.HasValue ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllRoomsInArea", areaParameter);
        }
    
        public virtual int dev_DeleteAllRoomsInAreaOnFloor(Nullable<int> area, Nullable<int> z)
        {
            var areaParameter = area.HasValue ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(int));
    
            var zParameter = z.HasValue ?
                new ObjectParameter("z", z) :
                new ObjectParameter("z", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllRoomsInAreaOnFloor", areaParameter, zParameter);
        }
    
        public virtual int dev_DeleteAllRoomStatesForRoom(Nullable<int> room)
        {
            var roomParameter = room.HasValue ?
                new ObjectParameter("room", room) :
                new ObjectParameter("room", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllRoomStatesForRoom", roomParameter);
        }
    
        public virtual int dev_DeleteAllVerbsForVerbType(Nullable<int> verbtype)
        {
            var verbtypeParameter = verbtype.HasValue ?
                new ObjectParameter("verbtype", verbtype) :
                new ObjectParameter("verbtype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllVerbsForVerbType", verbtypeParameter);
        }
    
        public virtual int dev_DeleteAllVerbTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_DeleteAllVerbTypes");
        }
    
        public virtual ObjectResult<dev_GetAction_Result> dev_GetAction(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAction_Result>("dev_GetAction", idParameter);
        }
    
        public virtual ObjectResult<dev_GetActionResult_Result> dev_GetActionResult(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetActionResult_Result>("dev_GetActionResult", idParameter);
        }
    
        public virtual ObjectResult<dev_GetAllActionResultsForAction_Result> dev_GetAllActionResultsForAction(Nullable<int> action)
        {
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllActionResultsForAction_Result>("dev_GetAllActionResultsForAction", actionParameter);
        }
    
        public virtual ObjectResult<dev_GetAllActionsForNoun_Result> dev_GetAllActionsForNoun(Nullable<int> noun)
        {
            var nounParameter = noun.HasValue ?
                new ObjectParameter("noun", noun) :
                new ObjectParameter("noun", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllActionsForNoun_Result>("dev_GetAllActionsForNoun", nounParameter);
        }
    
        public virtual ObjectResult<dev_GetAllAreas_Result> dev_GetAllAreas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllAreas_Result>("dev_GetAllAreas");
        }
    
        public virtual ObjectResult<dev_GetAllCharacterActionRequirementsForAction_Result> dev_GetAllCharacterActionRequirementsForAction(Nullable<int> action)
        {
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllCharacterActionRequirementsForAction_Result>("dev_GetAllCharacterActionRequirementsForAction", actionParameter);
        }
    
        public virtual ObjectResult<dev_GetAllCharacters_Result> dev_GetAllCharacters()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllCharacters_Result>("dev_GetAllCharacters");
        }
    
        public virtual ObjectResult<dev_GetAllEventActionRequirementsForAction_Result> dev_GetAllEventActionRequirementsForAction(Nullable<int> action)
        {
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllEventActionRequirementsForAction_Result>("dev_GetAllEventActionRequirementsForAction", actionParameter);
        }
    
        public virtual ObjectResult<dev_GetAllEvents_Result> dev_GetAllEvents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllEvents_Result>("dev_GetAllEvents");
        }
    
        public virtual ObjectResult<dev_GetAllItemActionRequirementsForAction_Result> dev_GetAllItemActionRequirementsForAction(Nullable<int> action)
        {
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllItemActionRequirementsForAction_Result>("dev_GetAllItemActionRequirementsForAction", actionParameter);
        }
    
        public virtual ObjectResult<dev_GetAllItems_Result> dev_GetAllItems()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllItems_Result>("dev_GetAllItems");
        }
    
        public virtual ObjectResult<dev_GetAllJSONPropertyDataTypes_Result> dev_GetAllJSONPropertyDataTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllJSONPropertyDataTypes_Result>("dev_GetAllJSONPropertyDataTypes");
        }
    
        public virtual ObjectResult<dev_GetAllLocations_Result> dev_GetAllLocations()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllLocations_Result>("dev_GetAllLocations");
        }
    
        public virtual ObjectResult<dev_GetAllMessageChoiceResultsForMessageChoice_Result> dev_GetAllMessageChoiceResultsForMessageChoice(Nullable<int> messagechoice)
        {
            var messagechoiceParameter = messagechoice.HasValue ?
                new ObjectParameter("messagechoice", messagechoice) :
                new ObjectParameter("messagechoice", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllMessageChoiceResultsForMessageChoice_Result>("dev_GetAllMessageChoiceResultsForMessageChoice", messagechoiceParameter);
        }
    
        public virtual ObjectResult<dev_GetAllMessageChoicesForMessage_Result> dev_GetAllMessageChoicesForMessage(Nullable<int> message)
        {
            var messageParameter = message.HasValue ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllMessageChoicesForMessage_Result>("dev_GetAllMessageChoicesForMessage", messageParameter);
        }
    
        public virtual ObjectResult<dev_GetAllMessages_Result> dev_GetAllMessages()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllMessages_Result>("dev_GetAllMessages");
        }
    
        public virtual ObjectResult<dev_GetAllNounsForParagraphState_Result> dev_GetAllNounsForParagraphState(Nullable<int> paragraphstate)
        {
            var paragraphstateParameter = paragraphstate.HasValue ?
                new ObjectParameter("paragraphstate", paragraphstate) :
                new ObjectParameter("paragraphstate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllNounsForParagraphState_Result>("dev_GetAllNounsForParagraphState", paragraphstateParameter);
        }
    
        public virtual ObjectResult<dev_GetAllParagraphsForRoom_Result> dev_GetAllParagraphsForRoom(Nullable<int> room)
        {
            var roomParameter = room.HasValue ?
                new ObjectParameter("room", room) :
                new ObjectParameter("room", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllParagraphsForRoom_Result>("dev_GetAllParagraphsForRoom", roomParameter);
        }
    
        public virtual ObjectResult<dev_GetAllParagraphsForRoomAndRoomState_Result> dev_GetAllParagraphsForRoomAndRoomState(Nullable<int> room, Nullable<int> roomstate)
        {
            var roomParameter = room.HasValue ?
                new ObjectParameter("room", room) :
                new ObjectParameter("room", typeof(int));
    
            var roomstateParameter = roomstate.HasValue ?
                new ObjectParameter("roomstate", roomstate) :
                new ObjectParameter("roomstate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllParagraphsForRoomAndRoomState_Result>("dev_GetAllParagraphsForRoomAndRoomState", roomParameter, roomstateParameter);
        }
    
        public virtual ObjectResult<dev_GetAllParagraphStatesForParagraph_Result> dev_GetAllParagraphStatesForParagraph(Nullable<int> paragraph)
        {
            var paragraphParameter = paragraph.HasValue ?
                new ObjectParameter("paragraph", paragraph) :
                new ObjectParameter("paragraph", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllParagraphStatesForParagraph_Result>("dev_GetAllParagraphStatesForParagraph", paragraphParameter);
        }
    
        public virtual ObjectResult<dev_GetAllResultsForActionResultType_Result> dev_GetAllResultsForActionResultType(Nullable<int> action)
        {
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllResultsForActionResultType_Result>("dev_GetAllResultsForActionResultType", actionParameter);
        }
    
        public virtual ObjectResult<dev_GetAllResultsForMessageChoiceResultType_Result> dev_GetAllResultsForMessageChoiceResultType(Nullable<int> messagechoice)
        {
            var messagechoiceParameter = messagechoice.HasValue ?
                new ObjectParameter("messagechoice", messagechoice) :
                new ObjectParameter("messagechoice", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllResultsForMessageChoiceResultType_Result>("dev_GetAllResultsForMessageChoiceResultType", messagechoiceParameter);
        }
    
        public virtual ObjectResult<dev_GetAllResultsForResultType_Result> dev_GetAllResultsForResultType(Nullable<int> resulttype)
        {
            var resulttypeParameter = resulttype.HasValue ?
                new ObjectParameter("resulttype", resulttype) :
                new ObjectParameter("resulttype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllResultsForResultType_Result>("dev_GetAllResultsForResultType", resulttypeParameter);
        }
    
        public virtual ObjectResult<dev_GetAllResultTypeJSONPropertiesForResultType_Result> dev_GetAllResultTypeJSONPropertiesForResultType(Nullable<int> resulttype)
        {
            var resulttypeParameter = resulttype.HasValue ?
                new ObjectParameter("resulttype", resulttype) :
                new ObjectParameter("resulttype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllResultTypeJSONPropertiesForResultType_Result>("dev_GetAllResultTypeJSONPropertiesForResultType", resulttypeParameter);
        }
    
        public virtual ObjectResult<dev_GetAllResultTypes_Result> dev_GetAllResultTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllResultTypes_Result>("dev_GetAllResultTypes");
        }
    
        public virtual ObjectResult<dev_GetAllRoomsInArea_Result> dev_GetAllRoomsInArea(Nullable<int> area)
        {
            var areaParameter = area.HasValue ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllRoomsInArea_Result>("dev_GetAllRoomsInArea", areaParameter);
        }
    
        public virtual ObjectResult<dev_GetAllRoomsInAreaOnFloor_Result> dev_GetAllRoomsInAreaOnFloor(Nullable<int> area, Nullable<int> z)
        {
            var areaParameter = area.HasValue ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(int));
    
            var zParameter = z.HasValue ?
                new ObjectParameter("z", z) :
                new ObjectParameter("z", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllRoomsInAreaOnFloor_Result>("dev_GetAllRoomsInAreaOnFloor", areaParameter, zParameter);
        }
    
        public virtual ObjectResult<dev_GetAllRoomStatesForRoom_Result> dev_GetAllRoomStatesForRoom(Nullable<int> room)
        {
            var roomParameter = room.HasValue ?
                new ObjectParameter("room", room) :
                new ObjectParameter("room", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllRoomStatesForRoom_Result>("dev_GetAllRoomStatesForRoom", roomParameter);
        }
    
        public virtual ObjectResult<dev_GetAllVerbsForVerbType_Result> dev_GetAllVerbsForVerbType(Nullable<int> verbtype)
        {
            var verbtypeParameter = verbtype.HasValue ?
                new ObjectParameter("verbtype", verbtype) :
                new ObjectParameter("verbtype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllVerbsForVerbType_Result>("dev_GetAllVerbsForVerbType", verbtypeParameter);
        }
    
        public virtual ObjectResult<dev_GetAllVerbTypes_Result> dev_GetAllVerbTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAllVerbTypes_Result>("dev_GetAllVerbTypes");
        }
    
        public virtual ObjectResult<dev_GetArea_Result> dev_GetArea(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetArea_Result>("dev_GetArea", idParameter);
        }
    
        public virtual ObjectResult<dev_GetAreaRoomOnInitialLoad_Result> dev_GetAreaRoomOnInitialLoad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetAreaRoomOnInitialLoad_Result>("dev_GetAreaRoomOnInitialLoad");
        }
    
        public virtual ObjectResult<dev_GetCharacter_Result> dev_GetCharacter(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetCharacter_Result>("dev_GetCharacter", idParameter);
        }
    
        public virtual ObjectResult<dev_GetCharacterActionRequirement_Result> dev_GetCharacterActionRequirement(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetCharacterActionRequirement_Result>("dev_GetCharacterActionRequirement", idParameter);
        }
    
        public virtual ObjectResult<dev_GetEvent_Result> dev_GetEvent(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetEvent_Result>("dev_GetEvent", idParameter);
        }
    
        public virtual ObjectResult<dev_GetEventActionRequirement_Result> dev_GetEventActionRequirement(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetEventActionRequirement_Result>("dev_GetEventActionRequirement", idParameter);
        }
    
        public virtual ObjectResult<dev_GetItem_Result> dev_GetItem(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetItem_Result>("dev_GetItem", idParameter);
        }
    
        public virtual ObjectResult<dev_GetItemActionRequirement_Result> dev_GetItemActionRequirement(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetItemActionRequirement_Result>("dev_GetItemActionRequirement", idParameter);
        }
    
        public virtual ObjectResult<dev_GetJSONPropertyDataType_Result> dev_GetJSONPropertyDataType(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetJSONPropertyDataType_Result>("dev_GetJSONPropertyDataType", idParameter);
        }
    
        public virtual ObjectResult<dev_GetLocation_Result> dev_GetLocation(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetLocation_Result>("dev_GetLocation", idParameter);
        }
    
        public virtual ObjectResult<dev_GetMessage_Result> dev_GetMessage(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetMessage_Result>("dev_GetMessage", idParameter);
        }
    
        public virtual ObjectResult<dev_GetMessageChoice_Result> dev_GetMessageChoice(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetMessageChoice_Result>("dev_GetMessageChoice", idParameter);
        }
    
        public virtual ObjectResult<dev_GetMessageChoiceResult_Result> dev_GetMessageChoiceResult(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetMessageChoiceResult_Result>("dev_GetMessageChoiceResult", idParameter);
        }
    
        public virtual ObjectResult<dev_GetNoun_Result> dev_GetNoun(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetNoun_Result>("dev_GetNoun", idParameter);
        }
    
        public virtual ObjectResult<dev_GetParagraph_Result> dev_GetParagraph(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetParagraph_Result>("dev_GetParagraph", idParameter);
        }
    
        public virtual ObjectResult<dev_GetParagraphState_Result> dev_GetParagraphState(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetParagraphState_Result>("dev_GetParagraphState", idParameter);
        }
    
        public virtual ObjectResult<dev_GetParagraphStateForParagraphPreview_Result> dev_GetParagraphStateForParagraphPreview(Nullable<int> state, Nullable<int> paragraph)
        {
            var stateParameter = state.HasValue ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(int));
    
            var paragraphParameter = paragraph.HasValue ?
                new ObjectParameter("paragraph", paragraph) :
                new ObjectParameter("paragraph", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetParagraphStateForParagraphPreview_Result>("dev_GetParagraphStateForParagraphPreview", stateParameter, paragraphParameter);
        }
    
        public virtual ObjectResult<dev_GetResult_Result> dev_GetResult(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetResult_Result>("dev_GetResult", idParameter);
        }
    
        public virtual ObjectResult<dev_GetResultType_Result> dev_GetResultType(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetResultType_Result>("dev_GetResultType", idParameter);
        }
    
        public virtual ObjectResult<dev_GetResultTypeJSONProperty_Result> dev_GetResultTypeJSONProperty(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetResultTypeJSONProperty_Result>("dev_GetResultTypeJSONProperty", idParameter);
        }
    
        public virtual ObjectResult<dev_GetRoom_Result> dev_GetRoom(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetRoom_Result>("dev_GetRoom", idParameter);
        }
    
        public virtual ObjectResult<dev_GetRoomPreviewParagraphStates_Result> dev_GetRoomPreview(Nullable<int> roompreview)
        {
            var roompreviewParameter = roompreview.HasValue ?
                new ObjectParameter("roompreview", roompreview) :
                new ObjectParameter("roompreview", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetRoomPreviewParagraphStates_Result>("dev_GetRoomPreview", roompreviewParameter);
        }
    
        public virtual ObjectResult<dev_GetRoomPreviewNouns_Result> dev_GetRoomPreviewNouns(Nullable<int> room)
        {
            var roomParameter = room.HasValue ?
                new ObjectParameter("room", room) :
                new ObjectParameter("room", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetRoomPreviewNouns_Result>("dev_GetRoomPreviewNouns", roomParameter);
        }
    
        public virtual ObjectResult<dev_GetRoomPreviewParagraphStates_Result> dev_GetRoomPreviewParagraphStates(Nullable<int> room)
        {
            var roomParameter = room.HasValue ?
                new ObjectParameter("room", room) :
                new ObjectParameter("room", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetRoomPreviewParagraphStates_Result>("dev_GetRoomPreviewParagraphStates", roomParameter);
        }
    
        public virtual ObjectResult<dev_GetRoomState_Result> dev_GetRoomState(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetRoomState_Result>("dev_GetRoomState", idParameter);
        }
    
        public virtual ObjectResult<dev_GetVerb_Result> dev_GetVerb(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetVerb_Result>("dev_GetVerb", idParameter);
        }
    
        public virtual ObjectResult<dev_GetVerbType_Result> dev_GetVerbType(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dev_GetVerbType_Result>("dev_GetVerbType", idParameter);
        }
    
        public virtual int dev_ImportAction(Nullable<int> id, Nullable<int> verbtype, Nullable<int> noun)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var verbtypeParameter = verbtype.HasValue ?
                new ObjectParameter("verbtype", verbtype) :
                new ObjectParameter("verbtype", typeof(int));
    
            var nounParameter = noun.HasValue ?
                new ObjectParameter("noun", noun) :
                new ObjectParameter("noun", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportAction", idParameter, verbtypeParameter, nounParameter);
        }
    
        public virtual int dev_ImportActionResult(Nullable<int> id, Nullable<int> result, Nullable<int> action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var resultParameter = result.HasValue ?
                new ObjectParameter("result", result) :
                new ObjectParameter("result", typeof(int));
    
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportActionResult", idParameter, resultParameter, actionParameter);
        }
    
        public virtual int dev_ImportArea(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportArea", idParameter, nameParameter);
        }
    
        public virtual int dev_ImportAreaRoomOnInitialLoad(Nullable<int> area, Nullable<int> room)
        {
            var areaParameter = area.HasValue ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(int));
    
            var roomParameter = room.HasValue ?
                new ObjectParameter("room", room) :
                new ObjectParameter("room", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportAreaRoomOnInitialLoad", areaParameter, roomParameter);
        }
    
        public virtual int dev_ImportCharacter(Nullable<int> id, string name, string description)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportCharacter", idParameter, nameParameter, descriptionParameter);
        }
    
        public virtual int dev_ImportCharacterActionRequirement(Nullable<int> id, Nullable<int> character, Nullable<int> action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var characterParameter = character.HasValue ?
                new ObjectParameter("character", character) :
                new ObjectParameter("character", typeof(int));
    
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportCharacterActionRequirement", idParameter, characterParameter, actionParameter);
        }
    
        public virtual int dev_ImportEvent(Nullable<int> id, string name, string description)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportEvent", idParameter, nameParameter, descriptionParameter);
        }
    
        public virtual int dev_ImportEventActionRequirement(Nullable<int> id, Nullable<int> @event, Nullable<int> action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var eventParameter = @event.HasValue ?
                new ObjectParameter("event", @event) :
                new ObjectParameter("event", typeof(int));
    
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportEventActionRequirement", idParameter, eventParameter, actionParameter);
        }
    
        public virtual int dev_ImportItem(Nullable<int> id, string name, string description)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportItem", idParameter, nameParameter, descriptionParameter);
        }
    
        public virtual int dev_ImportItemActionRequirement(Nullable<int> id, Nullable<int> item, Nullable<int> action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var itemParameter = item.HasValue ?
                new ObjectParameter("item", item) :
                new ObjectParameter("item", typeof(int));
    
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportItemActionRequirement", idParameter, itemParameter, actionParameter);
        }
    
        public virtual int dev_ImportJSONPropertyDataType(Nullable<int> id, string datatype)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var datatypeParameter = datatype != null ?
                new ObjectParameter("datatype", datatype) :
                new ObjectParameter("datatype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportJSONPropertyDataType", idParameter, datatypeParameter);
        }
    
        public virtual int dev_ImportLocation(Nullable<int> id, string name, string locationfile)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var locationfileParameter = locationfile != null ?
                new ObjectParameter("locationfile", locationfile) :
                new ObjectParameter("locationfile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportLocation", idParameter, nameParameter, locationfileParameter);
        }
    
        public virtual int dev_ImportMessage(Nullable<int> id, string name, string text)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportMessage", idParameter, nameParameter, textParameter);
        }
    
        public virtual int dev_ImportMessageChoice(Nullable<int> id, string name, string text, Nullable<int> message)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            var messageParameter = message.HasValue ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportMessageChoice", idParameter, nameParameter, textParameter, messageParameter);
        }
    
        public virtual int dev_ImportMessageChoiceResult(Nullable<int> id, Nullable<int> result, Nullable<int> messagechoice)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var resultParameter = result.HasValue ?
                new ObjectParameter("result", result) :
                new ObjectParameter("result", typeof(int));
    
            var messagechoiceParameter = messagechoice.HasValue ?
                new ObjectParameter("messagechoice", messagechoice) :
                new ObjectParameter("messagechoice", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportMessageChoiceResult", idParameter, resultParameter, messagechoiceParameter);
        }
    
        public virtual int dev_ImportNoun(Nullable<int> id, string text, Nullable<int> paragraphstate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            var paragraphstateParameter = paragraphstate.HasValue ?
                new ObjectParameter("paragraphstate", paragraphstate) :
                new ObjectParameter("paragraphstate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportNoun", idParameter, textParameter, paragraphstateParameter);
        }
    
        public virtual int dev_ImportParagraph(Nullable<int> id, Nullable<int> order, Nullable<int> room, Nullable<int> roomstate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var orderParameter = order.HasValue ?
                new ObjectParameter("order", order) :
                new ObjectParameter("order", typeof(int));
    
            var roomParameter = room.HasValue ?
                new ObjectParameter("room", room) :
                new ObjectParameter("room", typeof(int));
    
            var roomstateParameter = roomstate.HasValue ?
                new ObjectParameter("roomstate", roomstate) :
                new ObjectParameter("roomstate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportParagraph", idParameter, orderParameter, roomParameter, roomstateParameter);
        }
    
        public virtual int dev_ImportParagraphState(Nullable<int> id, Nullable<int> state, string text, Nullable<int> paragraph)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var stateParameter = state.HasValue ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(int));
    
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            var paragraphParameter = paragraph.HasValue ?
                new ObjectParameter("paragraph", paragraph) :
                new ObjectParameter("paragraph", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportParagraphState", idParameter, stateParameter, textParameter, paragraphParameter);
        }
    
        public virtual int dev_ImportResult(Nullable<int> id, string name, string jsondata, Nullable<int> resulttype)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var jsondataParameter = jsondata != null ?
                new ObjectParameter("jsondata", jsondata) :
                new ObjectParameter("jsondata", typeof(string));
    
            var resulttypeParameter = resulttype.HasValue ?
                new ObjectParameter("resulttype", resulttype) :
                new ObjectParameter("resulttype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportResult", idParameter, nameParameter, jsondataParameter, resulttypeParameter);
        }
    
        public virtual int dev_ImportResultType(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportResultType", idParameter, nameParameter);
        }
    
        public virtual int dev_ImportResultTypeJSONProperty(Nullable<int> id, string jsonproperty, Nullable<int> datatype, Nullable<int> resulttype)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var jsonpropertyParameter = jsonproperty != null ?
                new ObjectParameter("jsonproperty", jsonproperty) :
                new ObjectParameter("jsonproperty", typeof(string));
    
            var datatypeParameter = datatype.HasValue ?
                new ObjectParameter("datatype", datatype) :
                new ObjectParameter("datatype", typeof(int));
    
            var resulttypeParameter = resulttype.HasValue ?
                new ObjectParameter("resulttype", resulttype) :
                new ObjectParameter("resulttype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportResultTypeJSONProperty", idParameter, jsonpropertyParameter, datatypeParameter, resulttypeParameter);
        }
    
        public virtual int dev_ImportRoom(Nullable<int> id, string name, Nullable<int> x, Nullable<int> y, Nullable<int> z, Nullable<int> area)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var xParameter = x.HasValue ?
                new ObjectParameter("x", x) :
                new ObjectParameter("x", typeof(int));
    
            var yParameter = y.HasValue ?
                new ObjectParameter("y", y) :
                new ObjectParameter("y", typeof(int));
    
            var zParameter = z.HasValue ?
                new ObjectParameter("z", z) :
                new ObjectParameter("z", typeof(int));
    
            var areaParameter = area.HasValue ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportRoom", idParameter, nameParameter, xParameter, yParameter, zParameter, areaParameter);
        }
    
        public virtual int dev_ImportRoomState(Nullable<int> id, Nullable<int> state, Nullable<System.DateTime> time, Nullable<int> location, Nullable<int> room)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var stateParameter = state.HasValue ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(int));
    
            var timeParameter = time.HasValue ?
                new ObjectParameter("time", time) :
                new ObjectParameter("time", typeof(System.DateTime));
    
            var locationParameter = location.HasValue ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(int));
    
            var roomParameter = room.HasValue ?
                new ObjectParameter("room", room) :
                new ObjectParameter("room", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportRoomState", idParameter, stateParameter, timeParameter, locationParameter, roomParameter);
        }
    
        public virtual int dev_ImportVerb(Nullable<int> id, string name, Nullable<int> verbtype)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var verbtypeParameter = verbtype.HasValue ?
                new ObjectParameter("verbtype", verbtype) :
                new ObjectParameter("verbtype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportVerb", idParameter, nameParameter, verbtypeParameter);
        }
    
        public virtual int dev_ImportVerbType(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ImportVerbType", idParameter, nameParameter);
        }
    
        public virtual int dev_ShiftRoom(Nullable<int> id, Nullable<int> xIncr, Nullable<int> yIncr, Nullable<int> zIncr)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var xIncrParameter = xIncr.HasValue ?
                new ObjectParameter("xIncr", xIncr) :
                new ObjectParameter("xIncr", typeof(int));
    
            var yIncrParameter = yIncr.HasValue ?
                new ObjectParameter("yIncr", yIncr) :
                new ObjectParameter("yIncr", typeof(int));
    
            var zIncrParameter = zIncr.HasValue ?
                new ObjectParameter("zIncr", zIncr) :
                new ObjectParameter("zIncr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_ShiftRoom", idParameter, xIncrParameter, yIncrParameter, zIncrParameter);
        }
    
        public virtual int dev_UpdateAction(Nullable<int> id, Nullable<int> verbtype, Nullable<int> noun)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var verbtypeParameter = verbtype.HasValue ?
                new ObjectParameter("verbtype", verbtype) :
                new ObjectParameter("verbtype", typeof(int));
    
            var nounParameter = noun.HasValue ?
                new ObjectParameter("noun", noun) :
                new ObjectParameter("noun", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateAction", idParameter, verbtypeParameter, nounParameter);
        }
    
        public virtual int dev_UpdateActionResult(Nullable<int> id, Nullable<int> result, Nullable<int> action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var resultParameter = result.HasValue ?
                new ObjectParameter("result", result) :
                new ObjectParameter("result", typeof(int));
    
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateActionResult", idParameter, resultParameter, actionParameter);
        }
    
        public virtual int dev_UpdateArea(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateArea", idParameter, nameParameter);
        }
    
        public virtual int dev_UpdateCharacter(Nullable<int> id, string name, string description)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateCharacter", idParameter, nameParameter, descriptionParameter);
        }
    
        public virtual int dev_UpdateCharacterActionRequirement(Nullable<int> id, Nullable<int> item, Nullable<int> action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var itemParameter = item.HasValue ?
                new ObjectParameter("item", item) :
                new ObjectParameter("item", typeof(int));
    
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateCharacterActionRequirement", idParameter, itemParameter, actionParameter);
        }
    
        public virtual int dev_UpdateEvent(Nullable<int> id, string name, string description)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateEvent", idParameter, nameParameter, descriptionParameter);
        }
    
        public virtual int dev_UpdateEventActionRequirement(Nullable<int> id, Nullable<int> item, Nullable<int> action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var itemParameter = item.HasValue ?
                new ObjectParameter("item", item) :
                new ObjectParameter("item", typeof(int));
    
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateEventActionRequirement", idParameter, itemParameter, actionParameter);
        }
    
        public virtual int dev_UpdateItem(Nullable<int> id, string name, string description)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateItem", idParameter, nameParameter, descriptionParameter);
        }
    
        public virtual int dev_UpdateItemActionRequirement(Nullable<int> id, Nullable<int> item, Nullable<int> action)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var itemParameter = item.HasValue ?
                new ObjectParameter("item", item) :
                new ObjectParameter("item", typeof(int));
    
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateItemActionRequirement", idParameter, itemParameter, actionParameter);
        }
    
        public virtual int dev_UpdateJSONPropertyDataType(Nullable<int> id, string datatype)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var datatypeParameter = datatype != null ?
                new ObjectParameter("datatype", datatype) :
                new ObjectParameter("datatype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateJSONPropertyDataType", idParameter, datatypeParameter);
        }
    
        public virtual int dev_UpdateLocation(Nullable<int> id, string name, string locationfile)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var locationfileParameter = locationfile != null ?
                new ObjectParameter("locationfile", locationfile) :
                new ObjectParameter("locationfile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateLocation", idParameter, nameParameter, locationfileParameter);
        }
    
        public virtual int dev_UpdateMessage(Nullable<int> id, string name, string text)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateMessage", idParameter, nameParameter, textParameter);
        }
    
        public virtual int dev_UpdateMessageChoice(Nullable<int> id, string name, string text, Nullable<int> message)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            var messageParameter = message.HasValue ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateMessageChoice", idParameter, nameParameter, textParameter, messageParameter);
        }
    
        public virtual int dev_UpdateMessageChoiceResult(Nullable<int> id, Nullable<int> result, Nullable<int> messagechoice)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var resultParameter = result.HasValue ?
                new ObjectParameter("result", result) :
                new ObjectParameter("result", typeof(int));
    
            var messagechoiceParameter = messagechoice.HasValue ?
                new ObjectParameter("messagechoice", messagechoice) :
                new ObjectParameter("messagechoice", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateMessageChoiceResult", idParameter, resultParameter, messagechoiceParameter);
        }
    
        public virtual int dev_UpdateNoun(Nullable<int> id, string text, Nullable<int> paragraphstate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            var paragraphstateParameter = paragraphstate.HasValue ?
                new ObjectParameter("paragraphstate", paragraphstate) :
                new ObjectParameter("paragraphstate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateNoun", idParameter, textParameter, paragraphstateParameter);
        }
    
        public virtual int dev_UpdateParagraph(Nullable<int> id, Nullable<int> order, Nullable<int> room, Nullable<int> roomstate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var orderParameter = order.HasValue ?
                new ObjectParameter("order", order) :
                new ObjectParameter("order", typeof(int));
    
            var roomParameter = room.HasValue ?
                new ObjectParameter("room", room) :
                new ObjectParameter("room", typeof(int));
    
            var roomstateParameter = roomstate.HasValue ?
                new ObjectParameter("roomstate", roomstate) :
                new ObjectParameter("roomstate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateParagraph", idParameter, orderParameter, roomParameter, roomstateParameter);
        }
    
        public virtual int dev_UpdateParagraphState(Nullable<int> id, string text, Nullable<int> state, Nullable<int> paragraph)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            var stateParameter = state.HasValue ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(int));
    
            var paragraphParameter = paragraph.HasValue ?
                new ObjectParameter("paragraph", paragraph) :
                new ObjectParameter("paragraph", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateParagraphState", idParameter, textParameter, stateParameter, paragraphParameter);
        }
    
        public virtual int dev_UpdatePlayerHistory(Nullable<System.Guid> player, Nullable<int> evnt, Nullable<bool> inhistory)
        {
            var playerParameter = player.HasValue ?
                new ObjectParameter("player", player) :
                new ObjectParameter("player", typeof(System.Guid));
    
            var evntParameter = evnt.HasValue ?
                new ObjectParameter("evnt", evnt) :
                new ObjectParameter("evnt", typeof(int));
    
            var inhistoryParameter = inhistory.HasValue ?
                new ObjectParameter("inhistory", inhistory) :
                new ObjectParameter("inhistory", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdatePlayerHistory", playerParameter, evntParameter, inhistoryParameter);
        }
    
        public virtual int dev_UpdatePlayerInventory(Nullable<System.Guid> player, Nullable<int> item, Nullable<bool> ininventory)
        {
            var playerParameter = player.HasValue ?
                new ObjectParameter("player", player) :
                new ObjectParameter("player", typeof(System.Guid));
    
            var itemParameter = item.HasValue ?
                new ObjectParameter("item", item) :
                new ObjectParameter("item", typeof(int));
    
            var ininventoryParameter = ininventory.HasValue ?
                new ObjectParameter("ininventory", ininventory) :
                new ObjectParameter("ininventory", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdatePlayerInventory", playerParameter, itemParameter, ininventoryParameter);
        }
    
        public virtual int dev_UpdatePlayerParty(Nullable<System.Guid> player, Nullable<int> character, Nullable<bool> inparty)
        {
            var playerParameter = player.HasValue ?
                new ObjectParameter("player", player) :
                new ObjectParameter("player", typeof(System.Guid));
    
            var characterParameter = character.HasValue ?
                new ObjectParameter("character", character) :
                new ObjectParameter("character", typeof(int));
    
            var inpartyParameter = inparty.HasValue ?
                new ObjectParameter("inparty", inparty) :
                new ObjectParameter("inparty", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdatePlayerParty", playerParameter, characterParameter, inpartyParameter);
        }
    
        public virtual int dev_UpdateResult(Nullable<int> id, string name, string jsondata, Nullable<int> resulttype)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var jsondataParameter = jsondata != null ?
                new ObjectParameter("jsondata", jsondata) :
                new ObjectParameter("jsondata", typeof(string));
    
            var resulttypeParameter = resulttype.HasValue ?
                new ObjectParameter("resulttype", resulttype) :
                new ObjectParameter("resulttype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateResult", idParameter, nameParameter, jsondataParameter, resulttypeParameter);
        }
    
        public virtual int dev_UpdateResultType(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateResultType", idParameter, nameParameter);
        }
    
        public virtual int dev_UpdateResultTypeJSONProperty(Nullable<int> id, string jsonproperty, Nullable<int> datatype, Nullable<int> resulttype)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var jsonpropertyParameter = jsonproperty != null ?
                new ObjectParameter("jsonproperty", jsonproperty) :
                new ObjectParameter("jsonproperty", typeof(string));
    
            var datatypeParameter = datatype.HasValue ?
                new ObjectParameter("datatype", datatype) :
                new ObjectParameter("datatype", typeof(int));
    
            var resulttypeParameter = resulttype.HasValue ?
                new ObjectParameter("resulttype", resulttype) :
                new ObjectParameter("resulttype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateResultTypeJSONProperty", idParameter, jsonpropertyParameter, datatypeParameter, resulttypeParameter);
        }
    
        public virtual int dev_UpdateRoom(Nullable<int> id, string name, Nullable<int> x, Nullable<int> y, Nullable<int> z, Nullable<int> area)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var xParameter = x.HasValue ?
                new ObjectParameter("x", x) :
                new ObjectParameter("x", typeof(int));
    
            var yParameter = y.HasValue ?
                new ObjectParameter("y", y) :
                new ObjectParameter("y", typeof(int));
    
            var zParameter = z.HasValue ?
                new ObjectParameter("z", z) :
                new ObjectParameter("z", typeof(int));
    
            var areaParameter = area.HasValue ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateRoom", idParameter, nameParameter, xParameter, yParameter, zParameter, areaParameter);
        }
    
        public virtual int dev_UpdateRoomState(Nullable<int> id, Nullable<int> state, Nullable<System.DateTime> time, Nullable<int> location, Nullable<int> room)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var stateParameter = state.HasValue ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(int));
    
            var timeParameter = time.HasValue ?
                new ObjectParameter("time", time) :
                new ObjectParameter("time", typeof(System.DateTime));
    
            var locationParameter = location.HasValue ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(int));
    
            var roomParameter = room.HasValue ?
                new ObjectParameter("room", room) :
                new ObjectParameter("room", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateRoomState", idParameter, stateParameter, timeParameter, locationParameter, roomParameter);
        }
    
        public virtual int dev_UpdateVerb(Nullable<int> id, string name, Nullable<int> verbtype)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var verbtypeParameter = verbtype.HasValue ?
                new ObjectParameter("verbtype", verbtype) :
                new ObjectParameter("verbtype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateVerb", idParameter, nameParameter, verbtypeParameter);
        }
    
        public virtual int dev_UpdateVerbType(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpdateVerbType", idParameter, nameParameter);
        }
    
        public virtual int dev_UpsertAreaRoomOnInitialLoad(Nullable<int> area, Nullable<int> room)
        {
            var areaParameter = area.HasValue ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(int));
    
            var roomParameter = room.HasValue ?
                new ObjectParameter("room", room) :
                new ObjectParameter("room", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dev_UpsertAreaRoomOnInitialLoad", areaParameter, roomParameter);
        }
    }
}
